import sys
import os

env = Environment(CC        = '/opt/i586-mingw32/bin/i586-mingw32-gcc', 
                  CFLAGS    = os.getenv('CFLAGS', ''),
                  LINKFLAGS = '-s -nostdlib',
                  LIBS      = ['kernel32'],
                  ENV       = {'PATH': ['/opt/local/bin', '/usr/local/bin', '/bin', '/usr/bin']})
# if sys.platform.startswith('linux'):
#     env.Append(CFLAGS = ' -Wall -I/usr/include -I/usr/include/i386-linux-gnu -D__KLIBC__')
# else:
#     env.Append(CFLAGS = ' -Wall -IExamples/linux-usr-include -IExamples/linux-usr-include/i386-linux-gnu -D__KLIBC__')
# Export('env')
# 
# SConscript(['klibc/SConscript', 'libgcc/SConscript'])

# env.Program('strtoupper', ['strtoupper.c'])
env.Program('winhello.exe', ['cwcrt0.c', 'winhello.c'])
# env.Program('amifind', ['cwcrt0.c', 'amifind.c'] + Glob('klibc/*.o') + Glob('libgcc/*.o'))
# env.Program('memtest', ['cwcrt0.c', 'memtest.c'])
